<?php

namespace Database\Seeders;

use App\Enums\PostType;
use App\Models\Post;
use App\Models\Tag;
use App\Models\User;
use Illuminate\Database\Seeder;

class PostSeeder extends Seeder
{
    public function run(): void
    {
        $user = User::first();
        $tags = Tag::where('is_active', true)->get();

        $posts = [
            ['type' => PostType::EXPERIENCE, 'title' => 'Meine Erfahrungen mit Botulinumtoxin', 'content' => 'Nach Jahren mit Spastik habe ich endlich Botulinumtoxin-Injektionen ausprobiert. Die Wirkung setzte nach ca. 2 Wochen ein und ich konnte deutlich besser gehen. Die Muskeln fühlten sich lockerer an und die Schmerzen haben nachgelassen.'],
            ['type' => PostType::QUESTION, 'title' => 'Welche Hilfsmittel helfen bei starker Spastik im Arm?', 'content' => 'Ich habe seit einem Jahr zunehmend starke Spastik im rechten Arm. Kann mir jemand sagen, welche Hilfsmittel im Alltag wirklich helfen? Orthesen, Schienen oder anderes?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Wassergymnastik hat mein Leben verändert', 'content' => 'Seit ich zweimal pro Woche Wassergymnastik mache, hat sich meine Spastik deutlich verbessert. Das Wasser nimmt den Druck von den Muskeln und ich kann Bewegungen ausführen, die an Land unmöglich wären.'],
            ['type' => PostType::QUESTION, 'title' => 'Erfahrungen mit Baclofen-Pumpe?', 'content' => 'Mein Neurologe hat mir eine Baclofen-Pumpe empfohlen. Ich bin etwas unsicher wegen der OP. Hat jemand Erfahrungen damit? Was sollte ich wissen?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Physiotherapie dreimal die Woche – lohnt es sich?', 'content' => 'Ich mache jetzt seit 6 Monaten dreimal pro Woche Physiotherapie. Der Unterschied ist enorm. Die Therapeutin arbeitet gezielt an den spastischen Muskeln und kombiniert verschiedene Techniken.'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Magnesium gegen Muskelkrämpfe – mein Erfahrungsbericht', 'content' => 'Auf Empfehlung meines Arztes nehme ich jetzt Magnesium vor dem Schlafen. Die nächtlichen Krämpfe sind deutlich weniger geworden. Ich schlafe viel besser und die Muskeln fühlen sich morgens entspannter an.'],
            ['type' => PostType::QUESTION, 'title' => 'Reha-Einrichtungen – welche sind gut für Spastik?', 'content' => 'Ich suche eine spezialisierte Reha-Einrichtung für Spastik. Hat jemand persönliche Empfehlungen? Vor allem interessiert mich der süddeutsche Raum.'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Mit dem Rollstuhl reisen – meine Tipps', 'content' => 'Trotz Spastik und Rollstuhlnutzung bin ich letztes Jahr durch Portugal gereist. Mit der richtigen Planung ist vieles möglich. Hier sind meine wichtigsten Tipps für barrierefreies Reisen.'],
            ['type' => PostType::QUESTION, 'title' => 'Wie erkläre ich meinem Arbeitgeber meine Einschränkungen?', 'content' => 'Ich kehre nach einem Krankenhausaufenthalt an die Arbeit zurück. Meine Spastik ist jetzt stärker als vorher. Wie gehe ich das Gespräch mit dem Arbeitgeber am besten an?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Elektrische Rollstuhlsteuerung – welche Erfahrungen habt ihr?', 'content' => 'Ich habe auf einen elektrischen Rollstuhl umgestellt. Anfangs war die Steuerung durch die Spastik in meinen Händen schwierig, aber nach einigen Wochen Übung klappt es gut.'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Yoga speziell für Spastik – wirklich hilfreich', 'content' => 'Ich besuche seit drei Monaten eine spezielle Yoga-Klasse für Menschen mit Behinderungen. Die sanften Dehnungen helfen mir enorm. Die Lehrerin kennt sich mit Spastik aus und passt jede Übung an.'],
            ['type' => PostType::QUESTION, 'title' => 'Pflegerecht – welche Leistungen stehen mir zu?', 'content' => 'Ich habe Pflegegrad 3 und frage mich, ob ich alle mir zustehenden Leistungen bekomme. Hat jemand Erfahrung mit der Durchsetzung von Pflegeleistungen bei spastischen Lähmungen?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Wärme gegen Spastik – meine Methoden', 'content' => 'Wärme hilft mir sehr gegen die Muskelsteifheit. Ich nutze Wärmflaschen, Infrarotlampen und heiße Bäder. Vor allem morgens, wenn die Spastik am stärksten ist, macht Wärme einen riesigen Unterschied.'],
            ['type' => PostType::QUESTION, 'title' => 'Welche Medikamente helfen gegen Spastik am besten?', 'content' => 'Mein Arzt hat mir verschiedene Optionen vorgestellt: Baclofen, Tizanidin, Dantrium. Kann mir jemand von Erfahrungen berichten? Was hat geholfen, was hatte Nebenwirkungen?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Angehöriger mit Spastik – so unterstütze ich meinen Vater', 'content' => 'Mein Vater hat seit seinem Schlaganfall Spastik. Ich helfe ihm täglich. Hier teile ich, was wir gemeinsam gelernt haben: welche Hilfsmittel wirklich helfen und wie man den Alltag strukturiert.'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Spastik und Beruf – mein Weg zurück ins Arbeitsleben', 'content' => 'Nach meiner Diagnose dachte ich, ich könnte nie wieder arbeiten. Heute arbeite ich 25 Stunden pro Woche im Homeoffice. Es hat viel Anpassung gebraucht, aber es ist möglich.'],
            ['type' => PostType::QUESTION, 'title' => 'Kinderbetreuung mit Spastik – hat jemand Tipps?', 'content' => 'Ich bin Mutter von zwei Kindern und meine Spastik wird stärker. Ich suche praktische Tipps, wie man mit Einschränkungen dennoch für die Kinder da sein kann. Hilfsmittel, Alltagsstrategien?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Mein Erfahrungsbericht mit dem Elektrostimulationsgerät', 'content' => 'Mein Physiotherapeut hat mir ein FES-Gerät (Funktionelle Elektrostimulation) empfohlen. Nach 3 Monaten kann ich sagen: es hat mein Gangbild deutlich verbessert. Die Spastik im Fuß ist besser kontrollierbar.'],
            ['type' => PostType::QUESTION, 'title' => 'Schmerzen bei Spastik – wie geht ihr damit um?', 'content' => 'Meine Spastik verursacht starke Schmerzen, besonders nachts. Die normalen Schmerzmittel helfen kaum. Wie geht ihr mit spastikbedingten Schmerzen um? Welche Strategien helfen euch?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Neue Orthese – endlich die richtige gefunden', 'content' => 'Nach vielen schlechten Erfahrungen mit Orthesen habe ich jetzt eine maßgefertigte bekommen. Der Unterschied ist enorm. Die Anpassung dauerte 3 Termine, aber es hat sich absolut gelohnt.'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Meine Erfahrungen mit Botulinumtoxin', 'content' => 'Nach Jahren mit Spastik habe ich endlich Botulinumtoxin-Injektionen ausprobiert. Die Wirkung setzte nach ca. 2 Wochen ein und ich konnte deutlich besser gehen. Die Muskeln fühlten sich lockerer an und die Schmerzen haben nachgelassen.'],
            ['type' => PostType::QUESTION, 'title' => 'Welche Hilfsmittel helfen bei starker Spastik im Arm?', 'content' => 'Ich habe seit einem Jahr zunehmend starke Spastik im rechten Arm. Kann mir jemand sagen, welche Hilfsmittel im Alltag wirklich helfen? Orthesen, Schienen oder anderes?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Wassergymnastik hat mein Leben verändert', 'content' => 'Seit ich zweimal pro Woche Wassergymnastik mache, hat sich meine Spastik deutlich verbessert. Das Wasser nimmt den Druck von den Muskeln und ich kann Bewegungen ausführen, die an Land unmöglich wären.'],
            ['type' => PostType::QUESTION, 'title' => 'Erfahrungen mit Baclofen-Pumpe?', 'content' => 'Mein Neurologe hat mir eine Baclofen-Pumpe empfohlen. Ich bin etwas unsicher wegen der OP. Hat jemand Erfahrungen damit? Was sollte ich wissen?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Physiotherapie dreimal die Woche – lohnt es sich?', 'content' => 'Ich mache jetzt seit 6 Monaten dreimal pro Woche Physiotherapie. Der Unterschied ist enorm. Die Therapeutin arbeitet gezielt an den spastischen Muskeln und kombiniert verschiedene Techniken.'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Magnesium gegen Muskelkrämpfe – mein Erfahrungsbericht', 'content' => 'Auf Empfehlung meines Arztes nehme ich jetzt Magnesium vor dem Schlafen. Die nächtlichen Krämpfe sind deutlich weniger geworden. Ich schlafe viel besser und die Muskeln fühlen sich morgens entspannter an.'],
            ['type' => PostType::QUESTION, 'title' => 'Reha-Einrichtungen – welche sind gut für Spastik?', 'content' => 'Ich suche eine spezialisierte Reha-Einrichtung für Spastik. Hat jemand persönliche Empfehlungen? Vor allem interessiert mich der süddeutsche Raum.'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Mit dem Rollstuhl reisen – meine Tipps', 'content' => 'Trotz Spastik und Rollstuhlnutzung bin ich letztes Jahr durch Portugal gereist. Mit der richtigen Planung ist vieles möglich. Hier sind meine wichtigsten Tipps für barrierefreies Reisen.'],
            ['type' => PostType::QUESTION, 'title' => 'Wie erkläre ich meinem Arbeitgeber meine Einschränkungen?', 'content' => 'Ich kehre nach einem Krankenhausaufenthalt an die Arbeit zurück. Meine Spastik ist jetzt stärker als vorher. Wie gehe ich das Gespräch mit dem Arbeitgeber am besten an?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Elektrische Rollstuhlsteuerung – welche Erfahrungen habt ihr?', 'content' => 'Ich habe auf einen elektrischen Rollstuhl umgestellt. Anfangs war die Steuerung durch die Spastik in meinen Händen schwierig, aber nach einigen Wochen Übung klappt es gut.'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Yoga speziell für Spastik – wirklich hilfreich', 'content' => 'Ich besuche seit drei Monaten eine spezielle Yoga-Klasse für Menschen mit Behinderungen. Die sanften Dehnungen helfen mir enorm. Die Lehrerin kennt sich mit Spastik aus und passt jede Übung an.'],
            ['type' => PostType::QUESTION, 'title' => 'Pflegerecht – welche Leistungen stehen mir zu?', 'content' => 'Ich habe Pflegegrad 3 und frage mich, ob ich alle mir zustehenden Leistungen bekomme. Hat jemand Erfahrung mit der Durchsetzung von Pflegeleistungen bei spastischen Lähmungen?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Wärme gegen Spastik – meine Methoden', 'content' => 'Wärme hilft mir sehr gegen die Muskelsteifheit. Ich nutze Wärmflaschen, Infrarotlampen und heiße Bäder. Vor allem morgens, wenn die Spastik am stärksten ist, macht Wärme einen riesigen Unterschied.'],
            ['type' => PostType::QUESTION, 'title' => 'Welche Medikamente helfen gegen Spastik am besten?', 'content' => 'Mein Arzt hat mir verschiedene Optionen vorgestellt: Baclofen, Tizanidin, Dantrium. Kann mir jemand von Erfahrungen berichten? Was hat geholfen, was hatte Nebenwirkungen?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Angehöriger mit Spastik – so unterstütze ich meinen Vater', 'content' => 'Mein Vater hat seit seinem Schlaganfall Spastik. Ich helfe ihm täglich. Hier teile ich, was wir gemeinsam gelernt haben: welche Hilfsmittel wirklich helfen und wie man den Alltag strukturiert.'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Spastik und Beruf – mein Weg zurück ins Arbeitsleben', 'content' => 'Nach meiner Diagnose dachte ich, ich könnte nie wieder arbeiten. Heute arbeite ich 25 Stunden pro Woche im Homeoffice. Es hat viel Anpassung gebraucht, aber es ist möglich.'],
            ['type' => PostType::QUESTION, 'title' => 'Kinderbetreuung mit Spastik – hat jemand Tipps?', 'content' => 'Ich bin Mutter von zwei Kindern und meine Spastik wird stärker. Ich suche praktische Tipps, wie man mit Einschränkungen dennoch für die Kinder da sein kann. Hilfsmittel, Alltagsstrategien?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Mein Erfahrungsbericht mit dem Elektrostimulationsgerät', 'content' => 'Mein Physiotherapeut hat mir ein FES-Gerät (Funktionelle Elektrostimulation) empfohlen. Nach 3 Monaten kann ich sagen: es hat mein Gangbild deutlich verbessert. Die Spastik im Fuß ist besser kontrollierbar.'],
            ['type' => PostType::QUESTION, 'title' => 'Schmerzen bei Spastik – wie geht ihr damit um?', 'content' => 'Meine Spastik verursacht starke Schmerzen, besonders nachts. Die normalen Schmerzmittel helfen kaum. Wie geht ihr mit spastikbedingten Schmerzen um? Welche Strategien helfen euch?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Neue Orthese – endlich die richtige gefunden', 'content' => 'Nach vielen schlechten Erfahrungen mit Orthesen habe ich jetzt eine maßgefertigte bekommen. Der Unterschied ist enorm. Die Anpassung dauerte 3 Termine, aber es hat sich absolut gelohnt.'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Meine Erfahrungen mit Botulinumtoxin', 'content' => 'Nach Jahren mit Spastik habe ich endlich Botulinumtoxin-Injektionen ausprobiert. Die Wirkung setzte nach ca. 2 Wochen ein und ich konnte deutlich besser gehen. Die Muskeln fühlten sich lockerer an und die Schmerzen haben nachgelassen.'],
            ['type' => PostType::QUESTION, 'title' => 'Welche Hilfsmittel helfen bei starker Spastik im Arm?', 'content' => 'Ich habe seit einem Jahr zunehmend starke Spastik im rechten Arm. Kann mir jemand sagen, welche Hilfsmittel im Alltag wirklich helfen? Orthesen, Schienen oder anderes?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Wassergymnastik hat mein Leben verändert', 'content' => 'Seit ich zweimal pro Woche Wassergymnastik mache, hat sich meine Spastik deutlich verbessert. Das Wasser nimmt den Druck von den Muskeln und ich kann Bewegungen ausführen, die an Land unmöglich wären.'],
            ['type' => PostType::QUESTION, 'title' => 'Erfahrungen mit Baclofen-Pumpe?', 'content' => 'Mein Neurologe hat mir eine Baclofen-Pumpe empfohlen. Ich bin etwas unsicher wegen der OP. Hat jemand Erfahrungen damit? Was sollte ich wissen?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Physiotherapie dreimal die Woche – lohnt es sich?', 'content' => 'Ich mache jetzt seit 6 Monaten dreimal pro Woche Physiotherapie. Der Unterschied ist enorm. Die Therapeutin arbeitet gezielt an den spastischen Muskeln und kombiniert verschiedene Techniken.'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Magnesium gegen Muskelkrämpfe – mein Erfahrungsbericht', 'content' => 'Auf Empfehlung meines Arztes nehme ich jetzt Magnesium vor dem Schlafen. Die nächtlichen Krämpfe sind deutlich weniger geworden. Ich schlafe viel besser und die Muskeln fühlen sich morgens entspannter an.'],
            ['type' => PostType::QUESTION, 'title' => 'Reha-Einrichtungen – welche sind gut für Spastik?', 'content' => 'Ich suche eine spezialisierte Reha-Einrichtung für Spastik. Hat jemand persönliche Empfehlungen? Vor allem interessiert mich der süddeutsche Raum.'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Mit dem Rollstuhl reisen – meine Tipps', 'content' => 'Trotz Spastik und Rollstuhlnutzung bin ich letztes Jahr durch Portugal gereist. Mit der richtigen Planung ist vieles möglich. Hier sind meine wichtigsten Tipps für barrierefreies Reisen.'],
            ['type' => PostType::QUESTION, 'title' => 'Wie erkläre ich meinem Arbeitgeber meine Einschränkungen?', 'content' => 'Ich kehre nach einem Krankenhausaufenthalt an die Arbeit zurück. Meine Spastik ist jetzt stärker als vorher. Wie gehe ich das Gespräch mit dem Arbeitgeber am besten an?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Elektrische Rollstuhlsteuerung – welche Erfahrungen habt ihr?', 'content' => 'Ich habe auf einen elektrischen Rollstuhl umgestellt. Anfangs war die Steuerung durch die Spastik in meinen Händen schwierig, aber nach einigen Wochen Übung klappt es gut.'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Yoga speziell für Spastik – wirklich hilfreich', 'content' => 'Ich besuche seit drei Monaten eine spezielle Yoga-Klasse für Menschen mit Behinderungen. Die sanften Dehnungen helfen mir enorm. Die Lehrerin kennt sich mit Spastik aus und passt jede Übung an.'],
            ['type' => PostType::QUESTION, 'title' => 'Pflegerecht – welche Leistungen stehen mir zu?', 'content' => 'Ich habe Pflegegrad 3 und frage mich, ob ich alle mir zustehenden Leistungen bekomme. Hat jemand Erfahrung mit der Durchsetzung von Pflegeleistungen bei spastischen Lähmungen?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Wärme gegen Spastik – meine Methoden', 'content' => 'Wärme hilft mir sehr gegen die Muskelsteifheit. Ich nutze Wärmflaschen, Infrarotlampen und heiße Bäder. Vor allem morgens, wenn die Spastik am stärksten ist, macht Wärme einen riesigen Unterschied.'],
            ['type' => PostType::QUESTION, 'title' => 'Welche Medikamente helfen gegen Spastik am besten?', 'content' => 'Mein Arzt hat mir verschiedene Optionen vorgestellt: Baclofen, Tizanidin, Dantrium. Kann mir jemand von Erfahrungen berichten? Was hat geholfen, was hatte Nebenwirkungen?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Angehöriger mit Spastik – so unterstütze ich meinen Vater', 'content' => 'Mein Vater hat seit seinem Schlaganfall Spastik. Ich helfe ihm täglich. Hier teile ich, was wir gemeinsam gelernt haben: welche Hilfsmittel wirklich helfen und wie man den Alltag strukturiert.'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Spastik und Beruf – mein Weg zurück ins Arbeitsleben', 'content' => 'Nach meiner Diagnose dachte ich, ich könnte nie wieder arbeiten. Heute arbeite ich 25 Stunden pro Woche im Homeoffice. Es hat viel Anpassung gebraucht, aber es ist möglich.'],
            ['type' => PostType::QUESTION, 'title' => 'Kinderbetreuung mit Spastik – hat jemand Tipps?', 'content' => 'Ich bin Mutter von zwei Kindern und meine Spastik wird stärker. Ich suche praktische Tipps, wie man mit Einschränkungen dennoch für die Kinder da sein kann. Hilfsmittel, Alltagsstrategien?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Mein Erfahrungsbericht mit dem Elektrostimulationsgerät', 'content' => 'Mein Physiotherapeut hat mir ein FES-Gerät (Funktionelle Elektrostimulation) empfohlen. Nach 3 Monaten kann ich sagen: es hat mein Gangbild deutlich verbessert. Die Spastik im Fuß ist besser kontrollierbar.'],
            ['type' => PostType::QUESTION, 'title' => 'Schmerzen bei Spastik – wie geht ihr damit um?', 'content' => 'Meine Spastik verursacht starke Schmerzen, besonders nachts. Die normalen Schmerzmittel helfen kaum. Wie geht ihr mit spastikbedingten Schmerzen um? Welche Strategien helfen euch?'],
            ['type' => PostType::EXPERIENCE, 'title' => 'Neue Orthese – endlich die richtige gefunden', 'content' => 'Nach vielen schlechten Erfahrungen mit Orthesen habe ich jetzt eine maßgefertigte bekommen. Der Unterschied ist enorm. Die Anpassung dauerte 3 Termine, aber es hat sich absolut gelohnt.'],
        ];

        foreach ($posts as $index => $data) {
            $post = Post::create([
                'user_id' => $user->id,
                'title' => $data['title'],
                'content' => $data['content'],
                'type' => $data['type'],
                'is_published' => true,
                'published_at' => now()->subHours(count($posts) - $index),
            ]);

            $tag = $tags->random();
            $post->tags()->attach($tag->id);
        }
    }
}
